### ISSUE TITLE
Interesting...

### ISSUE THREAD

**Issue by WeLoveGaming** [1hAck-0/UE4-Cheat-Source-Code#2]
Interesting.... Any idea how to bypass Easy Anti Cheat?

**Comment by YMY1666527646** [comment]
Can sources be added for UE4 -4.26 ~ 4.27?

**Comment by 1hAck-0** [comment]
[**@YMY1666527646**](https://github.com/YMY1666527646) commented on [Jan 12, 2022, 8:37 PM GMT+1](https://github.com/1hAck-0/UE4-Cheat-Source-Code/issues/2#issuecomment-1011387735 "2022-01-12T19:37:53Z - Replied by Github Reply Comments"):
> Can sources be added for UE4 -4.26 ~ 4.27?

Yes, read the UE introduction and guide on this repository on how to make a similar cheat in any Unreal Engine game.

**Comment by 1hAck-0** [comment]
[**@WeLoveGaming**](https://github.com/WeLoveGaming) commented on [Jan 11, 2022, 10:53 PM GMT+1](https://github.com/1hAck-0/UE4-Cheat-Source-Code/issues/2#issue-1099650827 "2022-01-11T21:53:16Z - Replied by Github Reply Comments"):
> Interesting.... Any idea how to bypass Easy Anti Cheat?

Bypassing it is not easy and I am not familiar with anti-cheats, but I can give you a small tip: don't try to bypass EAC unless you already know every other concept of game hacking.

**Comment by ElectroGamesYT** [comment]
> [**@WeLoveGaming**](https://github.com/WeLoveGaming) commented on [Jan 11, 2022, 10:53 PM GMT+1](https://github.com/1hAck-0/UE4-Cheat-Source-Code/issues/2#issue-1099650827):
> 
> > Interesting.... Any idea how to bypass Easy Anti Cheat?
> 
> Bypassing it is not easy and I am not familiar with anti-cheats, but I can give you a small tip: don't try to bypass EAC unless you already know every other concept of game hacking.

Yes, I know how it works, I just have no idea how to make it to EAC doesn't block injections.

**Comment by WeLoveGaming** [comment]
> [**@WeLoveGaming**](https://github.com/WeLoveGaming) commented on [Jan 11, 2022, 10:53 PM GMT+1](https://github.com/1hAck-0/UE4-Cheat-Source-Code/issues/2#issue-1099650827):
> 
> > Interesting.... Any idea how to bypass Easy Anti Cheat?
> 
> Bypassing it is not easy and I am not familiar with anti-cheats, but I can give you a small tip: don't try to bypass EAC unless you already know every other concept of game hacking.

Yes, I know how it works, I just have no idea how to make it to EAC doesn't block injections.

**Comment by 1hAck-0** [comment]
[**@WeLoveGaming**](https://github.com/WeLoveGaming) commented on [Jan 14, 2022, 6:27 PM GMT+1](https://github.com/1hAck-0/UE4-Cheat-Source-Code/issues/2#issuecomment-1013316513 "2022-01-14T17:27:34Z - Replied by Github Reply Comments"):
> > [**@WeLoveGaming**](https://github.com/WeLoveGaming) commented on [Jan 11, 2022, 10:53 PM GMT+1](https://github.com/1hAck-0/UE4-Cheat-Source-Code/issues/2#issue-1099650827):
> > 
> > > Interesting.... Any idea how to bypass Easy Anti Cheat?
> > 
> > Bypassing it is not easy and I am not familiar with anti-cheats, but I can give you a small tip: don't try to bypass EAC unless you already know every other concept of game hacking.
> 
> Yes, I know how it works, I just have no idea how to make it to EAC doesn't block injections.

You can look up different injection methods, you will probably have to make your own undetected injector, and correct me if I am wrong but EAC is a kernel anti-cheat so you will have to bypass that somehow first because you can't open a handle to the process while EAC's kernel is running.
